language: cpp

sudo: required

compiler: clang

before_install:
  - sudo apt-get install opencl-headers

script:
  - clang++ -std=c++11 -lOpenCL detectCPUs.cpp -o detectCPUs && ./detectCPUs

notifications:
  email:
    on_success: change
    on_failure: change
