language: cpp

sudo: required

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers

script:
  - g++ detectCPUs.cpp -lOpenCL -o detectCPUs && ./detectCPUs

notifications:
  email:
    on_success: change
    on_failure: change
