language: cpp

sudo: required

compiler: gcc

before_install:
  - sudo apt-get install opencl-headers

script:
  - g++ -lOpenCL detectCPUs.cpp -o detectCPUs && ./detectCPUs

notifications:
  email:
    on_success: change
    on_failure: change
