#whitelist branches
branches:
  only:
    - master
    - linux

language: objective-c

sudo: required

compiler: clang

script:
  - clang++ -std=c++11 -framework OpenCL detectCPUs.cpp -o detectCPUs && ./detectCPUs

notifications:
  email:
    on_success: change
    on_failure: change
